/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;


import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Bean.Usuario;
import model.DAO.UsuarioDAO;

/**
 *
 * @author Senai
 */
public class TelaLogin extends javax.swing.JFrame {

    UsuarioDAO usuario = new UsuarioDAO();
    Usuario usu = new Usuario();

    /**
     * Creates new form TelaUsuario
     */
    public TelaLogin() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputSenha = new javax.swing.JPasswordField();
        inputUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(inputSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 650, 220, 20));
        getContentPane().add(inputUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 220, -1));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 800, 210, 50));

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 870, 120, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSenhaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        usu.setNomeUsuario(inputUser.getText());
        usu.setSenha(new String(inputSenha.getPassword()));

        if (usu.getNomeUsuario().trim().isEmpty()
                || usu.getSenha().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usuario Ou Senha Incorretos!");
        } else {

            Usuario ausu = (Usuario) usuario.logar(usu);

            if (Usuario.getIdUsuario() == 1) {

                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new TelaAdm().setVisible(true);
                    }
                });
                this.dispose();
            }
            
            if (Usuario.getIdUsuario() >= 2) {

                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new TelaPrincipal().setVisible(true);
                    }
                });
                this.dispose();
            }

        }      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        CriarConta TelaLogin = new CriarConta();
        this.dispose();
        TelaLogin.setVisible(true);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconeJanela.png")));
    }

}
