CREATE DATABASE DS_MERCADO;

USE DS_MERCADO;

CREATE TABLE USUARIO(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50),
SENHA VARCHAR(50)
);

CREATE TABLE ESTOQUE(
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(50),
CATEGORIA VARCHAR(50),
QUANTIDADE INT
);

CREATE TABLE PRODUTOS(
ID_PRODUTOS INT AUTO_INCREMENT
PRIMARY KEY,
NOME_PRODUTOS VARCHAR(50),
CATEGORIA VARCHAR(50),
QUANTIDADE INT,
PRECO float
);

CREATE TABLE PRODUTOS_C(
ID_PRODUTOS_C INT AUTO_INCREMENT PRIMARY KEY,
ESTOQUE_FK INT,
NOME_PRODUTOS_C VARCHAR(50),
FOREIGN KEY (ESTOQUE_FK) REFERENCES ESTOQUE (ID_ESTOQUE)
);

DELIMITER //
CREATE TRIGGER atualizar_estoque_frutas AFTER INSERT ON PRODUTOS
FOR EACH ROW
BEGIN
IF NEW.CATEGORIA = 'Frutas' THEN
UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE - NEW.QUANTIDADE WHERE CATEGORIA = 'Frutas';
END IF;
END;
//
DELIMITER ;

DELIMITER //
CREATE TRIGGER atualizar_estoque_carne AFTER INSERT ON PRODUTOS
FOR EACH ROW
BEGIN
IF NEW.CATEGORIA = 'Carne' THEN
UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE - NEW.QUANTIDADE WHERE CATEGORIA = 'Carne';
END IF;
END;
//
DELIMITER ;

DELIMITER //
CREATE TRIGGER atualizar_estoque_produto AFTER INSERT ON PRODUTOS
FOR EACH ROW
BEGIN
IF NEW.CATEGORIA = 'Produto de limpeza' THEN
UPDATE ESTOQUE SET QUANTIDADE = QUANTIDADE - NEW.QUANTIDADE WHERE CATEGORIA = 'Produto de limpeza';
END IF;
END;
//
DELIMITER ;

